# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_machineuser_place_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='serviceName',
            field=models.CharField(default='none', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serialNum',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='machineuser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='machine',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='userId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userguide',
            name='guideName',
            field=models.CharField(default='none', max_length=255, unique=True),
        ),
    ]
