# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170605_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Machine', to_field='serialNum'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Place', to_field='location'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serialNum',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Machine', to_field='serialNum'),
        ),
    ]
