# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170605_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineuser',
            name='location',
        ),
        migrations.AlterField(
            model_name='failure',
            name='reporterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.DeleteModel(
            name='MachineUser',
        ),
    ]
