# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_machineuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='scheduledAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
