# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170607_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='isBroken',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='scheduledAt',
            field=models.DateTimeField(default=b'2017-06-07 10:27:16'),
        ),
    ]
